FROM hub-mirrors.alauda.cn/library/eclipse-temurin:21-jdk-noble AS builder

ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US:en' \
    LC_ALL='en_US.UTF-8'

#
# SonarQube setup
#
ARG SONARQUBE_VERSION=26.1.0.118079
ENV DOCKER_RUNNING="true" \
    JAVA_HOME='/opt/java/openjdk' \
    SONARQUBE_HOME=/opt/sonarqube \
    SONAR_VERSION="${SONARQUBE_VERSION}" \
    SQ_DATA_DIR="/opt/sonarqube/data" \
    SQ_EXTENSIONS_DIR="/opt/sonarqube/extensions" \
    SQ_LOGS_DIR="/opt/sonarqube/logs" \
    SQ_TEMP_DIR="/opt/sonarqube/temp"

# Separate stage to use variable expansion
ENV ES_TMPDIR="${SQ_TEMP_DIR}"

RUN set -eux; \
    deluser ubuntu; \
    useradd --system --uid 1000 --gid 0 sonarqube; \
    apt-get update; \
    apt-get --no-install-recommends -y install \
        bash \
        curl \
        fonts-dejavu \
        gnupg \
        unzip \
        libgnutls30t64=3.8.3-1.1ubuntu3.5 \
        libssh-4=0.10.6-2ubuntu0.4;

COPY --chown=sonarsource:sonarsource source/sonar-application/build/distributions/sonar-application-${SONARQUBE_VERSION}.zip /home/sonarsource/
COPY --chown=sonarsource:sonarsource --chmod=555 image/community-build/jar-tools.sh /tmp/jar-tools.sh

RUN set -eux; \
    echo "networkaddress.cache.ttl=5" >> "${JAVA_HOME}/conf/security/java.security"; \
    sed --in-place --expression="s?securerandom.source=file:/dev/random?securerandom.source=file:/dev/urandom?g" "${JAVA_HOME}/conf/security/java.security"; \
    # pub   2048R/D26468DE 2015-05-25
    #       Key fingerprint = F118 2E81 C792 9289 21DB  CAB4 CFCA 4A29 D264 68DE
    # uid                  sonarsource_deployer (Sonarsource Deployer) <infra@sonarsource.com>
    # sub   2048R/06855C1D 2015-05-25
    unzip -q /home/sonarsource/sonar-application-${SONARQUBE_VERSION}.zip; \
    mv "sonarqube-${SONARQUBE_VERSION}" /opt/sonarqube; \
    rm /home/sonarsource/sonar-application-${SONARQUBE_VERSION}.zip*; \
    rm -rf ${SONARQUBE_HOME}/bin/*; \
    ln -s "${SONARQUBE_HOME}/lib/sonar-application-${SONARQUBE_VERSION}.jar" "${SONARQUBE_HOME}/lib/sonarqube.jar"; \
    chown -R sonarqube:root ${SONARQUBE_HOME}; \
    chown -R sonarqube:root "${SQ_DATA_DIR}" "${SQ_EXTENSIONS_DIR}" "${SQ_LOGS_DIR}" "${SQ_TEMP_DIR}"; \
    chmod -R 550 ${SONARQUBE_HOME}; \
    chmod -R 770 "${SQ_DATA_DIR}" "${SQ_EXTENSIONS_DIR}" "${SQ_LOGS_DIR}" "${SQ_TEMP_DIR}"; \
    apt-get remove -y gnupg unzip; \
    rm -rf /var/lib/apt/lists/*;

# renovate: datasource=maven depName=commons-lang3 lookupName=org.apache.commons:commons-lang3
ARG COMMONS_LANG3_VERSION=3.20.0
# renovate: datasource=maven depName=jackson-core lookupName=com.fasterxml.jackson.core:jackson-core
ARG JACKSON_CORE_FIXED_VERSION=2.21.2
RUN set -eux; \
    /tmp/jar-tools.sh replace "org.apache.commons" "commons-lang3" 3.9 "$COMMONS_LANG3_VERSION" "${SONARQUBE_HOME}/elasticsearch/modules/x-pack-inference/"; \
    /tmp/jar-tools.sh replace "com.fasterxml.jackson.core" "jackson-core" 2.15.0 2.18.6 "${SONARQUBE_HOME}/elasticsearch/modules/x-pack-inference/"; \
    /tmp/jar-tools.sh overlay-from-maven "com.fasterxml.jackson.core" "jackson-core" "${JACKSON_CORE_FIXED_VERSION}" "${SONARQUBE_HOME}/lib/extensions/sonar-python-plugin-5.19.0.32098.jar"; \
    /tmp/jar-tools.sh overlay-from-maven "com.fasterxml.jackson.core" "jackson-core" "${JACKSON_CORE_FIXED_VERSION}" "${SONARQUBE_HOME}/elasticsearch/bin/elasticsearch-sql-cli-8.19.13.jar"; \
    /tmp/jar-tools.sh overlay-from-maven "com.fasterxml.jackson.core" "jackson-core" "${JACKSON_CORE_FIXED_VERSION}" "${SONARQUBE_HOME}/elasticsearch/lib/elasticsearch-x-content-8.19.13.jar" "IMPL-JARS/x-content/jackson-core-2.17.2.jar"; \
    /tmp/jar-tools.sh overlay-from-maven "com.fasterxml.jackson.core" "jackson-core" "${JACKSON_CORE_FIXED_VERSION}" "${SONARQUBE_HOME}/elasticsearch/lib/tools/plugin-cli/elasticsearch-x-content-8.19.13.jar" "IMPL-JARS/x-content/jackson-core-2.17.2.jar"; \
    /tmp/jar-tools.sh overlay-from-maven "com.fasterxml.jackson.core" "jackson-core" "${JACKSON_CORE_FIXED_VERSION}" "${SONARQUBE_HOME}/lib/sonar-application-${SONARQUBE_VERSION}.jar"

COPY --chown=root:root --chmod=555 image/community-build/entrypoint.sh ${SONARQUBE_HOME}/docker/

# remove sniff tools
RUN set +e; \
  ls -d /usr/bin/* | grep -E "cpp|readelf|gcc|nc|netcat" | xargs rm; \
  rm /usr/lib/apt/methods/mirror

FROM hub-mirrors.alauda.cn/library/eclipse-temurin:21-jdk-noble

COPY --from=builder / /

LABEL io.k8s.description="SonarQube Community Build is a self-managed, automatic code review tool that systematically helps you deliver Clean Code."
LABEL io.openshift.min-cpu=400m
LABEL io.openshift.min-memory=2048M
LABEL io.openshift.non-scalable=true
LABEL io.openshift.tags=sonarqube,static-code-analysis,code-quality,clean-code
LABEL org.opencontainers.image.url=https://github.com/SonarSource/docker-sonarqube

ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US:en' \
    LC_ALL='en_US.UTF-8'

#
# SonarQube setup
#
ARG SONARQUBE_VERSION=26.1.0.118079
ENV DOCKER_RUNNING="true" \
    JAVA_HOME='/opt/java/openjdk' \
    SONARQUBE_HOME=/opt/sonarqube \
    SONAR_VERSION="${SONARQUBE_VERSION}" \
    SQ_DATA_DIR="/opt/sonarqube/data" \
    SQ_EXTENSIONS_DIR="/opt/sonarqube/extensions" \
    SQ_LOGS_DIR="/opt/sonarqube/logs" \
    SQ_TEMP_DIR="/opt/sonarqube/temp"

# Separate stage to use variable expansion
ENV ES_TMPDIR="${SQ_TEMP_DIR}"

VOLUME ["${SQ_DATA_DIR}", "${SQ_EXTENSIONS_DIR}", "${SQ_LOGS_DIR}", "${SQ_TEMP_DIR}"]

WORKDIR ${SONARQUBE_HOME}
EXPOSE 9000

USER sonarqube
STOPSIGNAL SIGINT

ENTRYPOINT ["/opt/sonarqube/docker/entrypoint.sh"]
